# This is a basic workflow to help you get started with Actions

name: flutter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Insert git sha
        run: |
          sed -i -e "s|GIT_SHA_REPLACE|$GITHUB_SHA|g" lib/config.dart
      - name: Insert build date
        run: |
          sed -i -e "s|BUILD_DATE_REPLACE|$(date)|g" lib/config.dart
      - name: Insert client cache busting
        run: |
          sed -i -e "s|CLIENT_VERSION_REPLACE|$(date +%s)|g" web/index.html
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.x'
      - run: flutter pub get
      #- run: flutter test
      - run: dart format --set-exit-if-changed lib
      - run: flutter analyze
      - uses: bluefireteam/flutter-gh-pages@v9
        with:
          compileToWasm: false # web.dart doesnt seem to work on chrome with wasm

  test-deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.x'
      - run: flutter build web

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './build/web'
          production-branch: master
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          deploy-message: "*Deploy from GitHub Actions*"
          enable-pull-request-comment: true
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          # fail if PR from fork that cant access secrets
          fails-without-credentials: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1